version: "0.1"
user: rahulkumarlambdatest
key: dboZK7so8koMnIR1tN11aKfMgxyKtDpb90IlyaCj4n6n7tQeK6
testSuites: [mvn test]
pre: [mkdir -p m2_cache_dir, mvn -Dmaven.repo.local=$CACHE_DIR -Dmaven.test.skip=true clean install]
preDirectives:
    commands: [mkdir -p m2_cache_dir, mvn -Dmaven.repo.local=$CACHE_DIR -Dmaven.test.skip=true clean install]
    maxRetries: 0
    shell: ""
    workingDirectory: ""
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
env:
    CACHE_DIR: m2_cache_dir
    TARGET_OS: Windows 10
runson: win
concurrency: 2
testSuiteTimeout: 90
cacheDirectories:
    - $CACHE_DIR
cacheKey: '{{ checksum "pom.xml" }}'
retryOnFailure: true
maxRetries: 1
jobID: 46e08b7d-2e0e-4d1a-b67d-1c7767700242
codeDirectory: KarateYTPractice
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: false
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
    baseCommand: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
sourcePayload:
    verifySSL: true
collectLocalGitData: true
dynamicAllocation: false
appium: false
